import { test, expect } from '@playwright/test';
interface BrowserTestState {
  peers: RTCPeerConnection[];
  screen?: MediaStreamTrack;
  captured: MediaStreamTrack[];
}
declare global {
  interface Window {
    meetingTest: BrowserTestState;
  }
}

test('fake-device WebRTC call, capacity, toggles, peer refresh, and leave', async ({ browser }) => {
  const a = await browser.newContext({ permissions: ['camera', 'microphone'] });
  const b = await browser.newContext({ permissions: ['camera', 'microphone'] });
  const page = await a.newPage(),
    other = await b.newPage();
  // Only the screen picker is simulated: sender replacement and RTP transport are native.
  for (const context of [a, b])
    await context.addInitScript(() => {
      window.meetingTest = { peers: [], captured: [] };
      const Original = window.RTCPeerConnection;
      window.RTCPeerConnection = class extends Original {
        constructor(config?: RTCConfiguration) {
          super(config);
          window.meetingTest.peers.push(this);
        }
      };
      navigator.mediaDevices.getDisplayMedia = async () => {
        const canvas = document.createElement('canvas');
        canvas.width = 640;
        canvas.height = 360;
        const drawing = canvas.getContext('2d')!;
        const paint = () => {
          drawing.fillStyle = '#bcf4a3';
          drawing.fillRect(0, 0, 640, 360);
          drawing.fillStyle = '#111513';
          drawing.fillText(String(Date.now()), 20, 30);
        };
        paint();
        const timer = setInterval(paint, 50);
        const stream = canvas.captureStream(20);
        const track = stream.getVideoTracks()[0];
        const stop = track.stop.bind(track);
        track.stop = () => {
          clearInterval(timer);
          stop();
        };
        window.meetingTest.screen = track;
        return stream;
      };
    });
  await page.goto('/');
  await page.bringToFront();
  await page.getByRole('button', { name: 'Create Meeting' }).click();
  await page.getByRole('button', { name: 'Enable camera & microphone' }).click();
  await expect(page.getByLabel('Your camera preview')).toHaveJSProperty('readyState', 4);
  await other.goto(page.url());
  await other.bringToFront();
  await other.getByRole('button', { name: 'Enable camera & microphone' }).click();
  await expect(other.getByLabel('Your camera preview')).toHaveJSProperty('readyState', 4);
  await page.getByRole('button', { name: 'Join Meeting', exact: true }).click();
  await expect(
    page.getByRole('status').filter({ hasText: 'Waiting for another participant' }),
  ).toBeVisible();
  await other.getByRole('button', { name: 'Join Meeting', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Connected' })).toBeVisible({
    timeout: 20000,
  });
  await expect(other.getByRole('status').filter({ hasText: 'Connected' })).toBeVisible();
  await page.bringToFront();
  await expect(page.getByLabel("Other participant's video")).toHaveJSProperty('readyState', 4);
  const third = await a.newPage();
  await third.goto(page.url());
  await third.getByRole('button', { name: 'Join Meeting', exact: true }).click();
  await expect(third.getByRole('heading', { name: 'Meeting room is full.' })).toBeVisible();
  await third.close();
  await page.getByRole('button', { name: 'Mute microphone' }).click();
  await expect(page.getByRole('button', { name: 'Unmute microphone' })).toHaveAttribute(
    'aria-pressed',
    'true',
  );
  expect(
    await page
      .getByLabel('Your video')
      .evaluate(
        (el: HTMLVideoElement) => (el.srcObject as MediaStream).getAudioTracks()[0].enabled,
      ),
  ).toBe(false);
  await page.getByRole('button', { name: 'Turn camera off' }).click();
  expect(
    await page
      .getByLabel('Your video')
      .evaluate(
        (el: HTMLVideoElement) => (el.srcObject as MediaStream).getVideoTracks()[0].enabled,
      ),
  ).toBe(false);
  for (const participant of [page, other]) {
    await participant.bringToFront();
    const cameraId = await participant
      .getByLabel('Your video')
      .evaluate((el: HTMLVideoElement) => (el.srcObject as MediaStream).getVideoTracks()[0].id);
    await participant.getByRole('button', { name: 'Share screen', exact: true }).click();
    await expect(participant.getByText('Your screen is being shared')).toBeVisible();
    expect(
      await participant.evaluate(
        () =>
          window.meetingTest.peers[0].getSenders().find((s) => s.track?.kind === 'video')?.track
            ?.id === window.meetingTest.screen?.id,
      ),
    ).toBe(true);
    // Simulates the ended event generated by the browser's own Stop sharing action.
    await participant.evaluate(() => {
      window.meetingTest.screen!.stop();
      window.meetingTest.screen!.dispatchEvent(new Event('ended'));
    });
    await expect(
      participant.getByRole('button', { name: 'Share screen', exact: true }),
    ).toBeVisible();
    expect(
      await participant.evaluate(
        () =>
          window.meetingTest.peers[0].getSenders().find((s) => s.track?.kind === 'video')?.track
            ?.id,
      ),
    ).toBe(cameraId);
    expect(await participant.evaluate(() => window.meetingTest.peers.length)).toBe(1);
    await participant.getByRole('button', { name: 'Share screen', exact: true }).click();
    await expect(participant.getByText('Your screen is being shared')).toBeVisible();
    await participant.getByRole('button', { name: 'Stop sharing', exact: true }).last().click();
    await expect(
      participant.getByRole('button', { name: 'Share screen', exact: true }),
    ).toBeVisible();
    expect(await participant.evaluate(() => window.meetingTest.screen?.readyState)).toBe('ended');
  }
  expect(
    await page
      .getByLabel('Your video')
      .evaluate(
        (el: HTMLVideoElement) => (el.srcObject as MediaStream).getVideoTracks()[0].enabled,
      ),
  ).toBe(false);
  await other.bringToFront();
  await other.reload();
  await expect(
    page.getByRole('status').filter({ hasText: 'Waiting for another participant' }),
  ).toBeVisible();
  await other.getByRole('button', { name: 'Enable camera & microphone' }).click();
  await expect(other.getByLabel('Your camera preview')).toHaveJSProperty('readyState', 4);
  await other.getByRole('button', { name: 'Join Meeting', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Connected' })).toBeVisible({
    timeout: 20000,
  });
  await page.getByLabel('Your video').evaluate((el: HTMLVideoElement) => {
    window.meetingTest.captured = (el.srcObject as MediaStream).getTracks();
  });
  await page.getByRole('button', { name: 'Leave meeting' }).click();
  expect(
    await page.evaluate(() => window.meetingTest.captured.every((t) => t.readyState === 'ended')),
  ).toBe(true);
  await expect(page.getByRole('heading', { name: 'Until next time.' })).toBeVisible();
  await expect(
    other.getByRole('status').filter({ hasText: 'Waiting for another participant' }),
  ).toBeVisible();
  await a.close();
  await b.close();
});
test('layouts fit mobile and desktop; invalid links remain actionable', async ({ page }) => {
  for (const width of [360, 768, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    await page.goto('/');
    expect(
      await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth),
    ).toBe(true);
    await page.screenshot({ path: `test-results/landing-${width}.png`, fullPage: true });
    await page.getByRole('button', { name: 'Create Meeting' }).click();
    await expect(page.getByRole('button', { name: 'Join Meeting', exact: true })).toBeVisible();
    expect(
      await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth),
    ).toBe(true);
    await page.screenshot({ path: `test-results/prejoin-${width}.png`, fullPage: true });
    await page.getByRole('button', { name: 'Join Meeting', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Leave meeting' })).toBeVisible();
    expect(
      await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth),
    ).toBe(true);
    await page.screenshot({ path: `test-results/call-${width}.png`, fullPage: true });
    await page.getByRole('button', { name: 'Leave meeting' }).click();
  }
  await page.goto('/#/room/not-valid');
  await expect(page.getByRole('heading', { name: 'This link needs another look.' })).toBeVisible();
});

test('denied permissions stay actionable and receive-only joining remains available', async ({
  page,
}) => {
  await page.addInitScript(() => {
    navigator.mediaDevices.getUserMedia = async () => {
      throw new DOMException('Denied', 'NotAllowedError');
    };
  });
  await page.goto('/');
  await page.getByRole('button', { name: 'Create Meeting' }).click();
  await page.getByRole('button', { name: 'Enable camera & microphone' }).click();
  await expect(page.getByRole('alert')).toContainText('Camera permission denied');
  await expect(page.getByRole('alert')).toContainText('Microphone permission denied');
  await page.getByRole('button', { name: 'Join Meeting', exact: true }).click();
  await expect(
    page.getByRole('status').filter({ hasText: 'Waiting for another participant' }),
  ).toBeVisible();
  await page.getByRole('button', { name: 'Leave meeting' }).click();
});
